/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
   // Khi bạn muốn Tailwind CSS luôn biên dịch các class động, bạn có thể khai báo chúng trong safelist.
   safelist: [
    'bg-red-3',
    'bg-blue-3',
    'bg-brand-3',
    'bg-green-3',
    'bg-black-3',
    'bg-gray-3',
    'bg-orange-3',
    'bg-skobeloff-3',
    'bg-yellow-3',
  ],
  theme: {
    colors: {
      border: '#C8C8CC',
      facebook: '#4267B2',
      zalo: '#0180C7',
      white: '#FFFFFF',
      brand: '#005BE0',
      'brand-1': '#5E98EB',
      'brand-2': '#C2D8F8',
      'brand-3': '#E6EFFC',
      'brand-hover': '#2E79E6',
      'brand-active': '#5E98EB',
      'brand-disabled': '#91B8F2',
      blue: '#005BE0',
      'blue-1': '#5E98EB',
      'blue-2': '#C2D8F8',
      'blue-3': '#E6EFFC',
      gray: '#808089',
      'gray-1': '#AFAFB5',
      'gray-2': '#E1E1E3',
      'gray-3': '#F2F2F3',
      'gray-4': '#F7F6F6',
      'gray-opacity': '#FFFFFF1A',
      red: '#FF424E',
      'red-1': '#FF99A0',
      'red-2': '#FFDBDE',
      'red-3': '#FFF0F1',
      green: '#00AB56',
      'green-1': '#78DA90',
      'green-2': '#D7FAE0',
      'green-3': '#EFFFF4',
      orange: '#E28F26',
      'orange-1': '#EDB876',
      'orange-2': '#F8E4CB',
      'orange-3': '#FCF4E9',
      skobeloff: '#006C81',
      'skobeloff-1': '#5EA2B0',
      'skobeloff-2': '#C2DCE1',
      'skobeloff-3': '#E6F0F2',
      yellow: '#FFB700',
      'yellow-1': '#FFD530',
      'yellow-2': '#FFF5C7',
      'yellow-3': '#FFFCED',

      black: '#3A3A3E',
      'black-1': '#5B5B61',
      'black-2': '#808089',
      'black-3': '#F2F2F3',

      secondary: '#5B5B61',
      tertiary: '#808089',
      quaternary: '#97979E',

      'primary': '#005BE0',

    },
    extend: {
      fontFamily: {},
      // fontSize: {
      //   xs: '12px',
      //   sm: '14px',
      //   base: '16px',
      //   lg: '18px',
      // },
      backgroundImage: {
        'bg-home-page': "url('/img/hero-pattern.svg')",
      },
      flex: {
        '1-auto': '1 0 auto',
        '0-auto': '0 0 auto'
      },
    },
  },
  plugins: [],
} 